
version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - pwd
      - ls -la
      - aws s3 sync ./ s3://sevenvista-test --delete
artifacts:
  files:
    - '**/*'
