
version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - pwd
      - ls -la
      - aws s3 rm --recursive s3://sevenvista-test
artifacts:
  files:
    - '**/*'
